### ISSUE TITLE
pcapfs crashing during mount: pcap4025059457531747034 not found in index!

### ISSUE THREAD

**Issue by dl8bh** [fkie-cad/pcapFS#11]
Hi,

I just found another bug with pcapfs crashing during the mount of a pcap dump:

```
root@pcapfs:/srv/pcapin# capinfos test_bigfile.pcap 
File name:           test_bigfile.pcap
File type:           Wireshark/tcpdump/... - pcap
File encapsulation:  Ethernet
File timestamp precision:  microseconds (6)
Packet size limit:   file hdr: 65535 bytes
Number of packets:   5.738 k
File size:           4.690 MB
Data size:           4.598 MB
Capture duration:    922,973750 seconds
First packet time:   2019-02-24 13:47:39,523289
Last packet time:    2019-02-24 14:03:02,420109
Data byte rate:      4.982 kBps
Data bit rate:       39 Mbps
Average packet size: 801,37 bytes
Average packet rate: 6.217 packets/s
Strict time order:   False
Number of interfaces in file: 1
Interface #0 info:
                     Encapsulation = Ethernet (1 - ether)
                     Capture length = 65535
                     Time precision = microseconds (6)
                     Time ticks per second = 1000000
                     Number of stat entries = 0
                     Number of packets = 5738633
```
```
root@pcapfs:/srv# pcapfs --sortby=/dstIP/srcIP/protocol/dstPort/srcPort ./pcapin/WAN_eth1.pcap ./pcapout/
2019-02-25 16:35:08.239604 | warning | Out of order packet not found!
2019-02-25 16:35:08.339694 | warning | Out of order packet not found!
2019-02-25 16:35:08.414885 | warning | Out of order packet not found!
.... many similar lines omitted
2019-02-25 16:35:41.918958 | warning | Out of order packet not found!
2019-02-25 16:35:41.987889 | warning | Out of order packet not found!
2019-02-25 16:35:42.110142 | warning | Out of order packet not found!
2019-02-25 16:35:56.387122 | error | pcap14538014902883075222 not found in index!
terminate called after throwing an instance of 'pcapfs::IndexError'
  what():  pcap14538014902883075222 not found in index!
Abgebrochen (Speicherabzug geschrieben)
```

Backtrace:
```

2019-02-25 16:42:55.322973 | warning | Out of order packet not found!
2019-02-25 16:42:55.442576 | warning | Out of order packet not found!
2019-02-25 16:43:09.551298 | error | pcap4025059457531747034 not found in index!
terminate called after throwing an instance of 'pcapfs::IndexError'
  what():  pcap4025059457531747034 not found in index!

Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff56e2801 in __GI_abort () at abort.c:79
#2  0x00007ffff5d378b7 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff5d3da06 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff5d3da41 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff5d3dc74 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00005555555e8084 in pcapfs::Index::get(std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned long> const&) const ()
#7  0x000055555568d231 in pcapfs::TcpFile::read(unsigned long, unsigned long, pcapfs::Index const&, char*) ()
#8  0x000055555563af5f in pcapfs::File::fillBuffer(pcapfs::Index const&) ()
#9  0x00005555555a2868 in getNextVirtualFile(std::vector<std::shared_ptr<pcapfs::File>, std::allocator<std::shared_ptr<pcapfs::File> > >, pcapfs::Index&) ()
#10 0x00005555555a317b in main ()
(gdb) 

```

**Comment by jhilgert** [comment]
So we've added some debug output in ef6a9e344bcd73309bbf03e0c30d4e058d5919e6, which should print the tcp connection with the wrong pcap reference just before everything crashes. Could you take a look at the output and afterwards the tcp connection and see if there is anything special (like a lot of missing packets etc.)? If possible, could you share the particular tcp connection?

**Comment by dl8bh** [comment]
I will look, if I can share the tcp connection
```
2019-03-11 15:26:08.766875 | error | reading from pcap id 0
2019-03-11 15:26:08.766905 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.766953 | error | reading from pcap id 0
2019-03-11 15:26:08.766983 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767032 | error | reading from pcap id 0
2019-03-11 15:26:08.767062 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767111 | error | reading from pcap id 0
2019-03-11 15:26:08.767141 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767190 | error | reading from pcap id 0
2019-03-11 15:26:08.767220 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767269 | error | reading from pcap id 0
2019-03-11 15:26:08.767299 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767349 | error | reading from pcap id 0
2019-03-11 15:26:08.767379 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767428 | error | reading from pcap id 0
2019-03-11 15:26:08.767459 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767509 | error | reading from pcap id 0
2019-03-11 15:26:08.767539 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767588 | error | reading from pcap id 0
2019-03-11 15:26:08.767617 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767683 | error | reading from pcap id 0
2019-03-11 15:26:08.767713 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767763 | error | reading from pcap id 0
2019-03-11 15:26:08.767794 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.767844 | error | reading from pcap id 9734813672639678618
2019-03-11 15:26:08.767875 | error | 172.23.42.23:35993 -> 192.168.23.42:80
2019-03-11 15:26:08.771368 | error | pcap9734813672639678618 not found in index!
terminate called after throwing an instance of 'pcapfs::IndexError'
  what():  pcap9734813672639678618 not found in index!
Abgebrochen (Speicherabzug geschrieben)


root@pcapfs:~# pcapfs.11 /srv/pcapin/test_bigfile.pcap /srv/pcapout/ 2>&1 |grep error | grep '192.168.23.42' | wc -l
122

```

**Comment by dl8bh** [comment]
I just exported all the traffic between the two ips using a wireshark filter (ip.addr==172.23.42.23) && (ip.addr==192.168.23.42).
The errors containing "reading from pcap id 0" persisted, but the 
"pcap9734813672639678618 not found in index!" did not occur again with this extract. the mount as such worked, but I have no idea, if its complete (because of the "reading from pcap id 0" errors)

**Comment by jhilgert** [comment]
The "error" output was just for debugging and not a real error, so the mount of the partial pcap should be fine. Could you check the new commit c9832b31c711473819a812675d6fe7c632f47e9e and provide us with the debug output before it crashes?
Also, can you take a look at the original pcap and see if there is more than one connection 172.23.42.23:35993 -> 192.168.23.42:80?

**Comment by dl8bh** [comment]
Its only one connection with 172.23.42.23:35993 -> 192.168.23.42:80.
Additional information in the attached logfile. 
Also, I attached a wireshark screenshot containing the most interesting parts with some TCP foo regarding duplicate acks, not captured segments etc that may have puzzled the software.

[crash_1918.log](https://github.com/fkie-cad/pcapFS/files/3003833/crash_1918.log)
![wireshark_issue11](https://user-images.githubusercontent.com/10435353/54928873-f0d5e280-4f14-11e9-8193-5e1cb1fbc901.png)
